### ISSUE TITLE
Web: Error upon creating RtcEngine (only in release mode)

### ISSUE THREAD

**Issue by NSFriend** [AgoraIO/Agora-Flutter-SDK#422]
**Description:**

Only in **web** release mode I got such error upon creating RtcEngine:

**PlatformException(error, NoSuchMethodError: method not found: 'setEventHandler' (k.setEventHandler is not a function), null, null)**

I call: `engine = await RtcEngine.create(GameInfo.currentGame.getAgoraKey());`

**SDK versions I use:**

Flutter (Channel stable, 2.2.3, on macOS 11.2 20D64 darwin-x64, locale en-GB)
agora_rtc_engine: ^4.1.0-alpha.2

**Comment by LichKing-2234** [comment]
pls follow dev/flutter2 branch, it has been fixed.

**Comment by NSFriend** [comment]
Thanks

**Comment by NSFriend** [comment]
@LichKing-2234 After switching to 

```
  agora_rtc_engine:
    git:
      url: git://github.com/AgoraIO/Flutter-SDK.git
      ref: dev/flutter2
```

function `RtcEngine.create` does not return at all

am I doing something wrong?
