### ISSUE TITLE
TMReachabilityCallback Crash 

### ISSUE THREAD

**Issue by nizwar** [AgoraIO/Agora-Flutter-SDK#744]
We got new crashes on production
![Screen Shot 2022-08-24 at 11 05 59](https://user-images.githubusercontent.com/33113137/186365089-6ddcba01-69b4-4336-b02e-f6081b3fd91f.png)
![Screen Shot 2022-08-24 at 11 06 07](https://user-images.githubusercontent.com/33113137/186365096-5c6be843-7926-46b4-85e2-404c88a35914.png)

We're not sure yet what happened, but the crash happened after user leaveChannel event triggered
![Screen Shot 2022-08-24 at 11 06 54](https://user-images.githubusercontent.com/33113137/186365459-a65319a6-84dd-4e7f-aee8-be10f0844994.png)

Happened only on iOS, for android we didnt get crash report for a while

**Comment by nizwar** [comment]
More context, we're using git version that fix #700 issue
```yaml
  agora_rtc_engine:
    git:
      url: https://github.com/AgoraIO/Agora-Flutter-SDK.git
      rel: master
```
